import { WorkspaceEditorialProfile } from './workspace-editorial.types';

export const workspaceEditorialProfiles: Record<string, WorkspaceEditorialProfile> = {
  passacumaru: {
    id: 'wep-passacumaru',
    workspaceId: 'passacumaru',
    name: 'PassaCumaru',
    niche: 'concursos publicos municipais',
    mission: 'Ser a principal referencia em informacoes sobre concursos publicos municipais do Brasil',
    vision: 'Ajudar milhares de concurseiros a conquistar a vaga dos sonhos',
    objectives: ['Aumentar trafego organico em 50% em 6 meses', 'Gerar 200 leads por mes via e-books', 'Posicionar para 50 palavras-chave relevantes'],
    targetAudience: 'Concurseiros que buscam concursos publicos municipais',
    personas: [
      { id: 'persona-concurseiro', name: 'Concurseiro Municipal', goals: ['Passar em concurso', 'Estudar de forma eficiente', 'Conhecer editais'], painPoints: ['Falta de tempo', 'Muita informacao dispersa', 'Edital complicado'], questions: ['Quando sai edital?', 'Como estudar para prefeitura?', 'Qual o salario?'], language: 'Simples e direto', knowledgeLevel: 'basico/intermediario', searchIntent: ['informativo', 'comparativo'], objections: ['Nao tenho tempo', 'Muito conteudo'], preferredCTAs: ['Baixar e-book', 'Ver editais'] },
    ],
    technicalLevel: 'basico',
    toneOfVoice: ['didatic', 'conversational'],
    depthLevel: 'deep',
    preferredFormat: 'artigo-guia',
    averageArticleSize: '2000-3500',
    monetization: { primaryMethod: 'e-books', secondaryMethods: ['assinaturas', 'afiliados'], ctaFocus: ['download', 'inscricao'], conversionGoals: ['download-ebook', 'assinatura'] },
    primaryCTA: 'Baixe nosso guia gratuito de concursos municipais',
    publicationFrequency: '3x por semana',
    language: 'pt-BR',
    country: 'BR',
    categories: [
      { id: 'cat-editais', name: 'Editais', subcategories: ['Editais abertos', 'Editais previstos', 'Resultado'], clusters: ['por-estado', 'por-municipio', 'por-cargo'], pillar: 'Guia de Editais Municipais' },
      { id: 'cat-legislacao', name: 'Legislacao', subcategories: ['Leis municipais', 'Constituicao', 'Regulamentacao'], clusters: ['direito-administrativo', 'direito-constitucional'], pillar: 'Legislacao para Concursos' },
      { id: 'cat-preparacao', name: 'Preparacao', subcategories: ['Como estudar', 'Cronograma', 'Materias'], clusters: ['metodologia', 'recursos', 'dicas'], pillar: 'Guia de Preparacao' },
    ],
    rules: { priorityThemes: ['editais', 'legislacao', 'preparacao', 'salarios', 'carreiras'], forbiddenThemes: ['conteudo adulto', 'violencia', 'discriminacao'], minWordCount: 1500, recommendedWordCount: 2500, useFAQ: true, useTables: true, useSchema: true, requiredCTAs: ['e-book', 'editais-relacionados'], editorialPolicies: ['fato-verificado', 'fonte-oficial', 'atualizacao-semanal'], adSensePolicies: ['min-800-palavras', 'max-3-ads'] },
    version: '1.0.0',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  qualoseguro: {
    id: 'wep-qualoseguro',
    workspaceId: 'qualoseguro',
    name: 'Qual o Seguro',
    niche: 'seguros e geracao de leads',
    mission: 'Conectar pessoas ao seguro ideal com comparativos transparentes',
    vision: 'Ser o portal de referencia em seguros do Brasil',
    objectives: ['Gerar 500 leads qualificados por mes', 'Aumentar conversao de formularios em 30%', 'Posicionar para top 20 keywords de seguros'],
    targetAudience: 'Pessoas e empresas buscando seguros',
    personas: [
      { id: 'persona-usuario', name: 'Buscador de Seguro', goals: ['Encontrar melhor seguro', 'Comparar precos', 'Entender coberturas'], painPoints: ['Muitas opcoes', 'Letra miuda', 'Duvidas sobre cobertura'], questions: ['Qual o melhor seguro auto?', 'Quanto custa seguro de vida?', 'Preciso de seguro residencial?'], language: 'Neutro e informativo', knowledgeLevel: 'basico', searchIntent: ['comparativo', 'transacional'], objections: ['Caro demais', 'Nao entendo', 'Confianca'], preferredCTAs: ['Cotar agora', 'Ver comparativo'] },
    ],
    technicalLevel: 'basico',
    toneOfVoice: ['institutional', 'conversational'],
    depthLevel: 'intermediate',
    preferredFormat: 'comparativo-guia',
    averageArticleSize: '1500-2500',
    monetization: { primaryMethod: 'leads', secondaryMethods: ['formularios', 'afiliados-seguros'], ctaFocus: ['cotacao', 'formulario'], conversionGoals: ['lead-qualificado', 'formulario-enviado'] },
    primaryCTA: 'Cote seu seguro gratuitamente',
    publicationFrequency: '4x por semana',
    language: 'pt-BR',
    country: 'BR',
    categories: [
      { id: 'cat-auto', name: 'Seguro Auto', subcategories: ['Cotacao', 'Comparativo', 'Cobertura'], clusters: ['por-marca', 'por-estado', 'por-perfil'], pillar: 'Guia de Seguro Auto' },
      { id: 'cat-vida', name: 'Seguro Vida', subcategories: ['Individual', 'Familiar', 'Empresarial'], clusters: ['por-idade', 'por-necessidade'], pillar: 'Guia de Seguro de Vida' },
      { id: 'cat-residencial', name: 'Seguro Residencial', subcategories: ['Apartamento', 'Casa', 'Comercial'], clusters: ['por-tipo', 'por-valor'], pillar: 'Guia de Seguro Residencial' },
    ],
    rules: { priorityThemes: ['seguros', 'comparativos', 'cotacoes', 'dicas-financeiras', 'protecao'], forbiddenThemes: ['investimentos arriscados', 'conselho-financeiro-personalizado'], minWordCount: 1200, recommendedWordCount: 2000, useFAQ: true, useTables: true, useSchema: true, requiredCTAs: ['cotacao', 'formulario'], editorialPolicies: ['dados-atualizados', 'fonte-oficial', 'transparencia'], adSensePolicies: ['min-800-palavras', 'max-3-ads'] },
    version: '1.0.0',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  utilprobrasil: {
    id: 'wep-utilprobrasil',
    workspaceId: 'utilprobrasil',
    name: 'UtilPro Brasil',
    niche: 'reviews, comparativos, utilidades e afiliados',
    mission: 'Ajudar profissionais e empresas a escolher as melhores ferramentas',
    vision: 'Ser a referencia em reviews de ferramentas SaaS e utilidades',
    objectives: ['Aumentar cliques em afiliados em 40%', 'Publicar 20 reviews por mes', 'Alcançar CTR de 3.5%'],
    targetAudience: 'Profissionais e empresas buscando ferramentas',
    personas: [
      { id: 'persona-profissional', name: 'Profissional de TI/Marketing', goals: ['Encontrar ferramenta ideal', 'Comparar opcoes', 'Economizar tempo'], painPoints: ['Muitas opcoes', 'Dificuldade de testar', 'Precos confusos'], questions: ['Qual a melhor ferramenta de email?', 'Como automatizar tarefas?', 'Vale a pena pagar?'], language: 'Tecnico mas acessivel', knowledgeLevel: 'intermediario/avancado', searchIntent: ['comparativo', 'avaliativo'], objections: ['Caro', 'Nao tenho tempo de testar', 'Muitas opcoes'], preferredCTAs: ['Ver review', 'Testar gratis'] },
    ],
    technicalLevel: 'intermediario',
    toneOfVoice: ['technical', 'editorial'],
    depthLevel: 'deep',
    preferredFormat: 'review-comparativo',
    averageArticleSize: '2000-4000',
    monetization: { primaryMethod: 'afiliados', secondaryMethods: ['comparativos', 'reviews-patrocinados'], ctaFocus: ['afiliado', 'teste-gratis'], conversionGoals: ['clique-afiliado', 'assinatura'] },
    primaryCTA: 'Confira nosso review completo',
    publicationFrequency: '3x por semana',
    language: 'pt-BR',
    country: 'BR',
    categories: [
      { id: 'cat-ferramentas', name: 'Ferramentas SaaS', subcategories: ['Email Marketing', 'CRM', 'Automacao', 'Design'], clusters: ['por-categoria', 'por-preco', 'por-tamanho'], pillar: 'Guia de Ferramentas SaaS' },
      { id: 'cat-produtividade', name: 'Produtividade', subcategories: ['Gestao de tempo', 'Colaboracao', 'Organizacao'], clusters: ['por-equipe', 'por-necessidade'], pillar: 'Guia de Produtividade' },
      { id: 'cat-tecnologia', name: 'Tecnologia', subcategories: ['Hardware', 'Software', 'Cloud'], clusters: ['por-uso', 'por-preco'], pillar: 'Guia de Tecnologia' },
    ],
    rules: { priorityThemes: ['reviews', 'comparativos', 'ferramentas', 'afiliados', 'produtividade'], forbiddenThemes: ['reviews falsos', 'promocao enganosa'], minWordCount: 1500, recommendedWordCount: 3000, useFAQ: true, useTables: true, useSchema: true, requiredCTAs: ['afiliado', 'review-completo'], editorialPolicies: ['teste-real', 'pros-e-contras', 'atualizacao-mensal'], adSensePolicies: ['min-800-palavras', 'max-3-ads'] },
    version: '1.0.0',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  tabuometro: {
    id: 'wep-tabuometro',
    workspaceId: 'tabuometro',
    name: 'Tabuometro',
    niche: 'portal editorial',
    mission: 'Publish conteudo relevante que gera engajamento e discussao',
    vision: 'Ser o portal de opiniao e analise mais lido do Brasil',
    objectives: ['Aumentar visitas recorrentes em 50%', 'Alcançar engajamento de 60%', 'Crescer base de leitores em 30%'],
    targetAudience: 'Publico geral interessado em opiniao e analise',
    personas: [
      { id: 'persona-leitor', name: 'Leitor de Portal', goals: ['Acompanhar tendencias', 'Ler opinioes relevantes', 'Compartilhar conteudo'], painPoints: ['Conteudo raso', 'Falta de profundidade', 'Clickbait'], questions: ['O que esta acontecendo?', 'Qual a opinao sobre?', 'Por que isso importa?'], language: 'Editorial e opinativo', knowledgeLevel: 'variado', searchIntent: ['informativo', 'opinativo'], objections: ['Conteudo repetido', 'Falta de profundidade'], preferredCTAs: ['Ler mais', 'Compartilhar', 'Assinar'] },
    ],
    technicalLevel: 'basico',
    toneOfVoice: ['editorial', 'inspirational'],
    depthLevel: 'moderate',
    preferredFormat: 'editorial-analise',
    averageArticleSize: '1200-2000',
    monetization: { primaryMethod: 'publicidade', secondaryMethods: ['conteudo-patrocinado', 'afiliados'], ctaFocus: ['assinatura', 'compartilhamento'], conversionGoals: ['leitor-recorrente', 'assinatura'] },
    primaryCTA: 'Inscreva-se para receber nossas analises',
    publicationFrequency: '5x por semana',
    language: 'pt-BR',
    country: 'BR',
    categories: [
      { id: 'cat-opiniao', name: 'Opiniao', subcategories: ['Editorial', 'Coluna', 'Analise'], clusters: ['politica', 'economia', 'cultura'], pillar: 'Espaco de Opiniao' },
      { id: 'cat-tendencias', name: 'Tendencias', subcategories: ['Tecnologia', 'Comportamento', 'Mercado'], clusters: ['por-tema', 'por-impacto'], pillar: 'Tendencias do Momento' },
      { id: 'cat-analise', name: 'Analise', subcategories: ['Profunda', 'Comparativa', 'Historica'], clusters: ['por-tema', 'por-periodo'], pillar: 'Analises Aprofundadas' },
    ],
    rules: { priorityThemes: ['opiniao', 'tendencias', 'analise', 'cultura', 'tecnologia'], forbiddenThemes: ['fake-news', 'discurso-odio', 'conteudo-adulto'], minWordCount: 1000, recommendedWordCount: 1500, useFAQ: false, useTables: false, useSchema: true, requiredCTAs: ['assinatura', 'compartilhamento'], editorialPolicies: ['opiniao-marcante', 'dados-reais', 'credibilidade'], adSensePolicies: ['min-800-palavras', 'max-3-ads'] },
    version: '1.0.0',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  aiagencyos: {
    id: 'wep-aiagencyos',
    workspaceId: 'aiagencyos',
    name: 'AI Agency OS',
    niche: 'autoridade, conhecimento e geracao de leads para servicos de IA',
    mission: 'Posicionar a agencia como autoridade em IA e automacao',
    vision: 'Ser a primeira opcao para empresas que buscam servicos de IA',
    objectives: ['Gerar 100 leads qualificados por mes', 'Agendar 20 reunioes por mes', 'Publicar 15 conteudos por mes'],
    targetAudience: 'Empresas e empreendedores buscando IA e automacao',
    personas: [
      { id: 'persona-empresario', name: 'Empresario Interessado em IA', goals: ['Automatizar processos', 'Reduzir custos', 'Aumentar produtividade'], painPoints: ['Nao sei por onde comecar', 'Muita informacao tecnica', 'Medo de investir errado'], questions: ['Como usar IA no meu negocio?', 'Quanto custa automatizar?', 'ROI e real?'], language: 'Profissional e consultivo', knowledgeLevel: 'basico/intermediario', searchIntent: ['informativo', 'transacional'], objections: ['Caro', 'Complexo', 'Nao sei se funciona'], preferredCTAs: ['Agendar reuniao', 'Ver cases'] },
    ],
    technicalLevel: 'intermediario',
    toneOfVoice: ['technical', 'institutional'],
    depthLevel: 'deep',
    preferredFormat: 'guia-case-study',
    averageArticleSize: '2000-3500',
    monetization: { primaryMethod: 'servicos', secondaryMethods: ['consultoria', 'projetos', 'demonstracoes'], ctaFocus: ['reuniao', 'proposta'], conversionGoals: ['reuniao-agendada', 'proposta-solicitada'] },
    primaryCTA: 'Agende uma conversa gratuita sobre IA',
    publicationFrequency: '3x por semana',
    language: 'pt-BR',
    country: 'BR',
    categories: [
      { id: 'cat-ia', name: 'Inteligencia Artificial', subcategories: ['Agentes IA', 'Automacao', 'LLMs'], clusters: ['por-caso-de-uso', 'por-tecnologia'], pillar: 'Guia de IA para Empresas' },
      { id: 'cat-automacao', name: 'Automacao', subcategories: ['Marketing', 'Vendas', 'Operacoes'], clusters: ['por-area', 'por-ferramenta'], pillar: 'Guia de Automacao' },
      { id: 'cat-cases', name: 'Cases de Sucesso', subcategories: ['Por industria', 'Por resultado'], clusters: ['por-tamanho', 'por-segmento'], pillar: 'Cases Reais de IA' },
    ],
    rules: { priorityThemes: ['ia', 'automacao', 'agentes', 'consultoria', 'cases'], forbiddenThemes: ['promessas-irreais', 'dados-falsos', 'medo'], minWordCount: 1500, recommendedWordCount: 2500, useFAQ: true, useTables: true, useSchema: true, requiredCTAs: ['reuniao', 'contato'], editorialPolicies: ['dados-reais', 'cases-verificados', 'transparencia'], adSensePolicies: ['min-800-palavras', 'max-3-ads'] },
    version: '1.0.0',
    updatedAt: '2026-07-03T00:00:00Z',
  },
};
