import { Guideline } from './knowledge.types';

export const guidelines: Guideline[] = [
  { id: 'gl-seo', name: 'Diretrizes SEO', category: 'guideline', subcategory: 'seo', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes de otimizacao para mecanismos de busca', rules: ['Title unico e descritivo com keyword principal', 'Meta description entre 150-160 caracteres', 'H1 unico por pagina', 'Estrutura H2/H3 hierarquica', 'Alt text descritivo em todas as imagens', 'Links internos relevantes', 'Schema JSON-LD valido', 'URL amigavel e curta'], examples: ['Title: "Guia Completo de SEO 2026 | PassaCumaru"', 'Meta: "Aprenda SEO do basico ao avancado. Dicas praticas para ranquear no Google."'], tags: ['seo', 'ranking'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'gl-adsense', name: 'Google AdSense', category: 'guideline', subcategory: 'adsense', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes de conformidade com Google AdSense', rules: ['Conteudo original e de alta qualidade', 'Minimo 800 palavras por pagina com ads', 'Max 3 unidades de anuncio por pagina', 'Nao inserir ads em paginas de erro', 'Nao usar pop-ups com ads', 'Respeitar politicas de conteudo'], examples: ['Banner responsivo no topo do conteudo', 'In-article ads entre paragrafos'], tags: ['adsense', 'monetizacao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'gl-tone', name: 'Tom de Voz', category: 'guideline', subcategory: 'tone', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes de tom de voz para conteudo', rules: ['Ser profissional mas acessivel', 'Evitar jargao tecnico desnecessario', 'Usar linguagem direta e clara', 'Manter tom consistente', 'Adaptar tom ao publico-alvo', 'Evitar ambiguidades'], examples: ['Bom: "Voce pode configurar em 3 passos simples"', 'Ruim: "A configuracao se da mediante a execucao do procedimento"'], tags: ['tom', 'voz', 'escrita'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'gl-readability', name: 'Legibilidade', category: 'guideline', subcategory: 'readability', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes de legibilidade do conteudo', rules: ['Paragrafos de no maximo 4 frases', 'Frases de no maximo 25 palavras', 'Usar listas e bullet points', 'Incluir subtitulos a cada 300 palavras', 'Evitar paragrafos longos', 'Usar palavras simples'], examples: ['Paragrafo curto com no maximo 3 linhas', 'Lista com 5-7 itens'], tags: ['legibilidade', 'formatacao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'gl-links', name: 'Links Internos e Externos', category: 'guideline', subcategory: 'links', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes para uso de links', rules: ['Minimo 3 links internos por artigo', 'Links internos para conteudo relevante', 'Links externos apenas para fontes confiaveis', 'Usar anchor text descritivo', 'Abrir links externos em nova aba', 'Verificar links periodicamente'], examples: ['<a href="/guia-seo">Guia de SEO</a>', '<a href="https://gov.br" target="_blank">Fonte oficial</a>'], tags: ['links', 'internos', 'externos'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'gl-schema', name: 'Schema Markup', category: 'guideline', subcategory: 'schema', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes para Schema.org', rules: ['Usar JSON-LD', 'Incluir @context e @type', 'Preencher todos os campos obrigatorios', 'Validar antes de publicar', 'Atualizar quando o conteudo mudar'], examples: ['{"@context":"https://schema.org","@type":"Article","headline":"..." }'], tags: ['schema', 'json-ld', 'structured-data'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'gl-ai-visibility', name: 'AI Visibility', category: 'guideline', subcategory: 'ai_visibility', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes para visibilidade em IA', rules: ['Estruturar conteudo com H2/H3 claros', 'Incluir dados e estatisticas', 'Citar fontes confiaveis', 'Responder perguntas diretamente', 'Usar tabelas para comparacoes', 'Manter dados atualizados'], examples: ['Tabela comparativa com dados atualizados', 'Secao "Perguntas Frequentes" com respostas diretas'], tags: ['ai', 'visibility', 'llm'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'gl-editorial', name: 'Diretrizes Editoriais', category: 'guideline', subcategory: 'editorial', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Diretrizes editoriais gerais', rules: ['Conteudo original e unico', 'Nao copiar de outros sites', 'Citar fontes quando necessario', 'Atualizar conteudo periodicamente', 'Manter calendario editorial', 'Revisar antes de publicar'], examples: ['Calendario editorial mensal', 'Checklist de revisao pre-publicacao'], tags: ['editorial', 'qualidade'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
];
