import { Playbook } from './knowledge.types';

export const playbooks: Playbook[] = [
  { id: 'pb-seo', name: 'SEO', category: 'playbook', subcategory: 'seo', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook completo de SEO para organico', steps: ['Pesquisa de palavras-chave', 'Analise de concorrencia', 'Otimizacao on-page', 'Link building', 'Monitoramento'], bestPractices: ['Title unico e descritivo', 'Meta description com CTA', 'Alt text em todas as imagens', 'Links internos estruturados', 'Schema markup'], tags: ['seo', 'organico', 'ranking'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-ai-visibility', name: 'AI Visibility', category: 'playbook', subcategory: 'ai_visibility', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Otimizacao para visibilidade em respostas de IA', steps: ['Estruturar H2/H3 claros', 'Incluir dados atualizados', 'Usar fontes confiaveis', 'Respostas diretas', 'Schema completo'], bestPractices: ['Responder perguntas diretamente', 'Usar listas e tabelas', 'Incluir estatisticas', 'Citar fontes', 'Manter atualizado'], tags: ['ai', 'visibility', 'llm'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-writing', name: 'Writing', category: 'playbook', subcategory: 'writing', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de escrita de conteudo', steps: ['Pesquisa', 'Esquema', 'Escrita', 'Revisao', 'Publicacao'], bestPractices: ['Tom consistente', 'Paragrafos curtos', 'Subtitulos claros', 'CTA relevante', 'Formatting adequado'], tags: ['writing', 'conteudo', 'redacao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-research', name: 'Research', category: 'playbook', subcategory: 'research', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de pesquisa de conteudo', steps: ['Definir escopo', 'Fontes primarias', 'Fontes secundarias', 'Validacao', 'Sintese'], bestPractices: ['Usar fontes oficiais', 'Verificar dados', 'Citar origens', 'Atualizar informacoes', 'Documentar fontes'], tags: ['research', 'pesquisa', 'dados'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-qa', name: 'QA', category: 'playbook', subcategory: 'qa', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de quality assurance', steps: ['Verificacao gramatical', 'Verificacao factual', 'Verificacao SEO', 'Verificacao de links', 'Verificacao final'], bestPractices: ['Revisar erros comuns', 'Verificar links quebrados', 'Testar mobile', 'Validar dados', 'Checar conformidade'], tags: ['qa', 'qualidade', 'revisao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-publishing', name: 'Publishing', category: 'playbook', subcategory: 'publishing', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de publicacao', steps: ['Preview', 'Aprovacao', 'Publicacao', 'Revalidacao', 'Monitoramento'], bestPractices: ['Sempre preview antes', 'Confirmar aprovacao humana', 'Verificar formatacao', 'Testar links', 'Monitorar performance'], tags: ['publishing', 'publicacao', 'deploy'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-reviews', name: 'Reviews', category: 'playbook', subcategory: 'reviews', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de reviews de produtos', steps: ['Pesquisa do produto', 'Analise de features', 'Comparacao', 'Pros/Contras', 'Recomendacao'], bestPractices: ['Ser imparcial', 'Incluir dados reais', 'Comparar com concorrentes', 'Atualizar periodicamente', 'Incluir imagens'], tags: ['reviews', 'produtos', 'comparativos'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-landing-pages', name: 'Landing Pages', category: 'playbook', subcategory: 'landing', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de landing pages', steps: ['Definir objetivo', 'Copy', 'Design', 'CTA', 'Teste A/B'], bestPractices: ['Foco em uma acao', 'Copy persuasiva', 'CTA claro', 'Social proof', 'Mobile first'], tags: ['landing', 'conversao', 'ctr'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-ebooks', name: 'E-books', category: 'playbook', subcategory: 'ebook', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de e-books', steps: ['Pesquisa aprofundada', 'Esquema', 'Escrita', 'Revisao', 'Design', 'Publicacao'], bestPractices: ['Conteudo valioso', 'Estrutura clara', 'Design profissional', 'CTA para download', 'Gated content'], tags: ['ebook', 'lead magnet', 'conteudo'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-newsletters', name: 'Newsletters', category: 'playbook', subcategory: 'newsletter', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de newsletters', steps: ['Curadoria', 'Redacao', 'Revisao', 'Agendamento', 'Envio'], bestPractices: ['Assunto persuasivo', 'Conteudo relevante', 'Frequency consistente', 'Segmentacao', 'A/B test'], tags: ['newsletter', 'email', 'engajamento'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-refresh', name: 'Refresh', category: 'playbook', subcategory: 'refresh', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de refresh de conteudo', steps: ['Analise de performance', 'Identificacao de gaps', 'Atualizacao', 'Reescrita', 'Republicacao'], bestPractices: ['Manter URL', 'Redirecionar se necessario', 'Atualizar dados', 'Melhorar SEO', 'Notificar Google'], tags: ['refresh', 'atualizacao', 'manutencao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'pb-business-outcome', name: 'Business Outcome', category: 'playbook', subcategory: 'business', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Playbook de resultados de negocio', steps: ['Definir KPIs', 'Medir', 'Analisar', 'Otimizar', 'Reportar'], bestPractices: ['Focar em ROI', 'Medir conversoes', 'A/B test continuo', 'Iterar rapidamente', 'Documentar aprendizados'], tags: ['business', 'roi', 'metricas'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
];
