import { PromptTemplate } from './knowledge.types';

export const promptLibrary: PromptTemplate[] = [
  { id: 'prompt-research', name: 'Pesquisa de Conteudo', category: 'prompt', subcategory: 'research', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para pesquisa de conteudo', promptText: 'Pesquise sobre {topic} para o workspace {workspace}. Identifique: 1) Principais subtopicos, 2) Dados estatisticos relevantes, 3) Fontes confiaveis, 4) Gaps de conteudo. Retorne um relatorio estruturado.', variables: ['topic', 'workspace'], priority: 1, tags: ['research', 'pesquisa'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'prompt-writing', name: 'Escrita de Artigo', category: 'prompt', subcategory: 'writing', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para escrita de artigo', promptText: 'Escreva um artigo sobre {topic} com {size} palavras. Tom: {tone}. Publico: {audience}. Inclua: introducao, desenvolvimento com H2/H3, conclusao com CTA. Otimizado para SEO e AI Visibility.', variables: ['topic', 'size', 'tone', 'audience'], priority: 1, tags: ['writing', 'artigo'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'prompt-seo', name: 'Otimizacao SEO', category: 'prompt', subcategory: 'seo', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para otimizacao SEO', promptText: 'Otimize o conteudo para SEO: 1) Title otimizado com keyword, 2) Meta description com CTA, 3) Headings H2/H3 com keyword, 4) Alt text nas imagens, 5) Links internos, 6) Schema markup.', variables: [], priority: 2, tags: ['seo', 'otimizacao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'prompt-review', name: 'Revisao Editorial', category: 'prompt', subcategory: 'editorial', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para revisao editorial', promptText: 'Revise o conteudo verificando: 1) Gramatica e ortografia, 2) Coerencia e fluidez, 3) Tom de voz, 4) Dados factuais, 5) Links, 6) Formatacao. Retorne correcoes sugeridas.', variables: [], priority: 2, tags: ['review', 'revisao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'prompt-faq', name: 'Geracao de FAQ', category: 'prompt', subcategory: 'faq', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para geracao de FAQ', promptText: 'Gere 10 perguntas frequentes sobre {topic} com respostas diretas e concisas. Cada resposta deve ter 2-3 frases. Otimizado para AI Visibility e Featured Snippets.', variables: ['topic'], priority: 3, tags: ['faq', 'perguntas'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'prompt-schema', name: 'Geracao de Schema', category: 'prompt', subcategory: 'schema', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para geracao de Schema', promptText: 'Gere o Schema.org JSON-LD para o conteudo: {type}. Inclua: titulo, descricao, autor, dataPublicacao, imagem. Valido e sem erros.', variables: ['type'], priority: 3, tags: ['schema', 'json-ld'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'prompt-title', name: 'Geracao de Titulos', category: 'prompt', subcategory: 'title', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para geracao de titulos', promptText: 'Gere 5 titulos para {topic}: 1) SEO otimizado, 2) Clickbait etico, 3) Informativo, 4) Lista, 5) Pergunta. Maximo 60 caracteres.', variables: ['topic'], priority: 2, tags: ['titulo', 'headline'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'prompt-summary', name: 'Resumo Executivo', category: 'prompt', subcategory: 'summary', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Prompt para resumo executivo', promptText: 'Crie um resumo executivo de {content} em 3 paragrafos: contexto, achados principais, recomendacoes.', variables: ['content'], priority: 3, tags: ['resumo', 'executivo'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
];
