import { ContentTemplate } from './knowledge.types';

export const templates: ContentTemplate[] = [
  { id: 'tpl-article', name: 'Artigo Completo', category: 'template', subcategory: 'article', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Template para artigo completo', structure: ['# {title}', '', '## Introducao', '{introduction}', '', '## {section1_h2}', '{section1_content}', '', '### {section1_h3}', '{section1_h3_content}', '', '## {section2_h2}', '{section2_content}', '', '## Conclusao', '{conclusion}', '', '**CTA:** {cta}'], placeholders: ['title', 'introduction', 'section1_h2', 'section1_content', 'section1_h3', 'section1_h3_content', 'section2_h2', 'section2_content', 'conclusion', 'cta'], tags: ['artigo', 'conteudo'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'tpl-guide', name: 'Guia Completo', category: 'template', subcategory: 'guide', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Template para guia passo a passo', structure: ['# {title}', '', '> {subtitle}', '', '## O que voce vai aprender', '{objectives}', '', '## Pre-requisitos', '{prerequisites}', '', '## Passo 1: {step1}', '{step1_content}', '', '## Passo 2: {step2}', '{step2_content}', '', '## Conclusao', '{conclusion}'], placeholders: ['title', 'subtitle', 'objectives', 'prerequisites', 'step1', 'step1_content', 'step2', 'step2_content', 'conclusion'], tags: ['guia', 'tutorial'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'tpl-faq', name: 'FAQ', category: 'template', subcategory: 'faq', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Template para pagina de FAQ', structure: ['# {title}', '', '## {question1}', '{answer1}', '', '## {question2}', '{answer2}', '', '## {question3}', '{answer3}', '', '## {question4}', '{answer4}', '', '## {question5}', '{answer5}'], placeholders: ['title', 'question1', 'answer1', 'question2', 'answer2', 'question3', 'answer3', 'question4', 'answer4', 'question5', 'answer5'], tags: ['faq', 'perguntas'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'tpl-review', name: 'Review Comparativo', category: 'template', subcategory: 'review', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Template para review comparativo', structure: ['# {title}', '', '## Visao Geral', '{overview}', '', '## {product1}', '{product1_details}', '', '## {product2}', '{product2_details}', '', '## Comparacao', '{comparison_table}', '', '## Pros e Contras', '{pros_cons}', '', '## Veredito', '{verdict}', '', '**CTA:** {cta}'], placeholders: ['title', 'overview', 'product1', 'product1_details', 'product2', 'product2_details', 'comparison_table', 'pros_cons', 'verdict', 'cta'], tags: ['review', 'comparativo'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'tpl-checklist', name: 'Checklist', category: 'template', subcategory: 'checklist', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Template para checklist', structure: ['# {title}', '', '> {description}', '', '## Itens', '- [ ] {item1}', '- [ ] {item2}', '- [ ] {item3}', '- [ ] {item4}', '- [ ] {item5}'], placeholders: ['title', 'description', 'item1', 'item2', 'item3', 'item4', 'item5'], tags: ['checklist', 'lista'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'tpl-case-study', name: 'Estudo de Caso', category: 'template', subcategory: 'case-study', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Template para estudo de caso', structure: ['# {title}', '', '## Contexto', '{context}', '', '## Desafio', '{challenge}', '', '## Solucao', '{solution}', '', '## Resultados', '{results}', '', '## Lições Aprendidas', '{lessons}'], placeholders: ['title', 'context', 'challenge', 'solution', 'results', 'lessons'], tags: ['estudo', 'caso'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'tpl-pillar', name: 'Pagina Pilar', category: 'template', subcategory: 'pillar', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Template para pagina pilar', structure: ['# {title}', '', '## Introducao', '{introduction}', '', '## {topic1}', '{topic1_content}', '', '### {subtopic1_1}', '{subtopic1_1_content}', '', '## {topic2}', '{topic2_content}', '', '## {topic3}', '{topic3_content}', '', '## Recursos Adicionais', '{resources}', '', '## Conclusao', '{conclusion}'], placeholders: ['title', 'introduction', 'topic1', 'topic1_content', 'subtopic1_1', 'subtopic1_1_content', 'topic2', 'topic2_content', 'topic3', 'topic3_content', 'resources', 'conclusion'], tags: ['pilar', 'hub'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
];
