import { WorkspaceKnowledge } from './knowledge.types';

export const workspaceKnowledge: WorkspaceKnowledge[] = [
  { id: 'wk-passacumaru', name: 'Concursos Publicos Municipais', category: 'workspace_knowledge', subcategory: 'concursos', workspaceId: 'passacumaru', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Conhecimento sobre concursos publicos municipais do Brasil', domain: 'concursos', subtopics: ['Editais', 'Legislacao', 'IVIN', 'Perfil dos candidatos', 'Concursos por estado', 'Concursos por municipio', 'Remuneracao', 'Beneficios', 'Preparacao', 'Estudo'], tags: ['concursos', 'publicos', 'municipais'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'wk-qualoseguro', name: 'Seguros e Geracao de Leads', category: 'workspace_knowledge', subcategory: 'seguros', workspaceId: 'qualoseguro', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Conhecimento sobre seguros e geracao de leads', domain: 'seguros', subtopics: ['Seguro auto', 'Seguro residencial', 'Seguro vida', 'Seguro empresarial', 'Comparativos', 'Cotacoes', 'Leads qualificados', 'Funil de conversao', 'CTAs', 'Formularios'], tags: ['seguros', 'leads', 'conversao'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'wk-utilpro', name: 'Reviews e Afiliados', category: 'workspace_knowledge', subcategory: 'reviews', workspaceId: 'utilprobrasil', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Conhecimento sobre reviews, comparativos e marketing de afiliados', domain: 'reviews', subtopics: ['Reviews de ferramentas', 'Comparativos', 'Afiliados', 'Comissao', 'CTR', 'Conversao', 'Ferramentas SaaS', 'Produtividade', 'Tecnologia', 'Negocios'], tags: ['reviews', 'afiliados', 'comparativos'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'wk-tabuometro', name: 'Portal Editorial', category: 'workspace_knowledge', subcategory: 'editorial', workspaceId: 'tabuometro', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Conhecimento sobre portal editorial e conteudo de opiniao', domain: 'editorial', subtopics: ['Editorias', 'Opiniao', 'Analise', 'Tendencias', 'Engajamento', 'Recorrencia', 'Compartilhamentos', 'Crescimento', 'Publicidade', 'Afiliados'], tags: ['editorial', 'opiniao', 'portal'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
  { id: 'wk-aiagency', name: 'Servicos de IA e Automacao', category: 'workspace_knowledge', subcategory: 'ia', workspaceId: 'aiagencyos', language: 'pt-BR', version: '1.0.0', status: 'active', author: 'system', content: 'Conhecimento sobre servicos de IA, automacao e consultoria', domain: 'ia', subtopics: ['Inteligencia Artificial', 'Automacao', 'Agentes IA', 'Consultoria', 'Casos de uso', 'ROI', 'Implementacao', 'Stack tecnologica', 'Cases reais', 'Leads'], tags: ['ia', 'automacao', 'consultoria'], createdAt: '2026-07-03T00:00:00Z', updatedAt: '2026-07-03T00:00:00Z' },
];
