import { Opportunity, OpportunityType } from './opportunity.types';

const preloaded: Opportunity[] = [
  { id: 'opp-001', workspaceId: 'passacumaru', type: 'new-cluster', title: 'Cluster Gastronomia Nordestina', description: 'Novo cluster de receitas nordestinas com 8 artigos', origin: 'Opportunity Intelligence', estimatedImpact: 85, estimatedEffort: 60, risk: 25, confidence: 0.88, priority: 82, suggestedMission: 'Criar cluster gastronomia nordestina', status: 'detected', scores: { opportunityScore: 82, impactScore: 85, effortScore: 40, strategicValue: 78, revenuePotential: 65, aiVisibilityPotential: 80, organicGrowthPotential: 88, finalPriorityScore: 82 }, createdAt: '2026-07-03T10:00:00Z' },
  { id: 'opp-002', workspaceId: 'passacumaru', type: 'content-update', title: 'Atualizar artigos do cluster viagens', description: 'Revisar e atualizar 10 artigos existentes', origin: 'Auto Learning', estimatedImpact: 60, estimatedEffort: 30, risk: 10, confidence: 0.92, priority: 75, suggestedMission: 'Atualizar conteudo cluster viagens', status: 'detected', scores: { opportunityScore: 75, impactScore: 60, effortScore: 70, strategicValue: 65, revenuePotential: 40, aiVisibilityPotential: 55, organicGrowthPotential: 62, finalPriorityScore: 75 }, createdAt: '2026-07-03T09:00:00Z' },
  { id: 'opp-003', workspaceId: 'passacumaru', type: 'emerging-trend', title: 'Tendencia: Turismo Regenerativo', description: 'Trend emergente com potencial de trafego alto', origin: 'Google Trends', estimatedImpact: 90, estimatedEffort: 70, risk: 35, confidence: 0.78, priority: 80, suggestedMission: 'Explorar tendencia turismo regenerativo', status: 'detected', scores: { opportunityScore: 80, impactScore: 90, effortScore: 30, strategicValue: 85, revenuePotential: 70, aiVisibilityPotential: 92, organicGrowthPotential: 85, finalPriorityScore: 80 }, createdAt: '2026-07-03T08:00:00Z' },
  { id: 'opp-004', workspaceId: 'garimpeibrasil', type: 'new-pillar-page', title: 'Pagina Pilar Guia de Ferramentas', description: 'Criar pagina pilar abrangente sobre ferramentas', origin: 'Content Intelligence', estimatedImpact: 75, estimatedEffort: 50, risk: 20, confidence: 0.85, priority: 72, suggestedMission: 'Criar pagina pilar ferramentas', status: 'detected', scores: { opportunityScore: 72, impactScore: 75, effortScore: 50, strategicValue: 70, revenuePotential: 55, aiVisibilityPotential: 78, organicGrowthPotential: 72, finalPriorityScore: 72 }, createdAt: '2026-07-03T07:00:00Z' },
  { id: 'opp-005', workspaceId: 'garimpeibrasil', type: 'ai-optimization', title: 'Otimizar para AI Overview', description: 'Adaptar conteudo para visibilidade em AI Overviews', origin: 'Predictive Intelligence', estimatedImpact: 70, estimatedEffort: 40, risk: 15, confidence: 0.82, priority: 70, suggestedMission: 'Otimizar conteudo para AI Overview', status: 'detected', scores: { opportunityScore: 70, impactScore: 70, effortScore: 60, strategicValue: 72, revenuePotential: 50, aiVisibilityPotential: 90, organicGrowthPotential: 68, finalPriorityScore: 70 }, createdAt: '2026-07-03T06:00:00Z' },
  { id: 'opp-006', workspaceId: 'passacumaru', type: 'traffic-recovery', title: 'Recuperar trafego artigos sazonais', description: 'Reativar artigos de alta temporada', origin: 'Monitoring Agent', estimatedImpact: 55, estimatedEffort: 20, risk: 10, confidence: 0.9, priority: 65, suggestedMission: 'Recuperar trafego sazonal', status: 'detected', scores: { opportunityScore: 65, impactScore: 55, effortScore: 80, strategicValue: 50, revenuePotential: 35, aiVisibilityPotential: 45, organicGrowthPotential: 58, finalPriorityScore: 65 }, createdAt: '2026-07-03T05:00:00Z' },
];

export function detectOpportunities(): Opportunity[] { return preloaded; }
export function getOpportunityById(id: string): Opportunity | undefined { return preloaded.find(o => o.id === id); }
export function getOpportunitiesByWorkspace(ws: string): Opportunity[] { return preloaded.filter(o => o.workspaceId === ws); }
