import { WorkflowDefinition } from './workflow.types';

export const workflowTemplates: Record<string, WorkflowDefinition> = {
  article: {
    id: 'tpl-article',
    name: 'Artigo Completo',
    description: 'Fluxo para criacao de artigo: research, escrita, revisao e publicacao',
    category: 'content',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'research', name: 'Pesquisa', type: 'agent', agentType: 'content-intelligence', queue: 'content', dependsOn: [], conditions: [], retryOnFail: true, optional: false },
      { id: 'write', name: 'Escrita', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['research'], conditions: [], retryOnFail: true, optional: false },
      { id: 'review', name: 'Revisao', type: 'agent', agentType: 'authority-intelligence', queue: 'content', dependsOn: ['write'], conditions: [], retryOnFail: false, optional: false },
      { id: 'approval', name: 'Aprovacao Humana', type: 'approval', dependsOn: ['review'], conditions: [{ type: 'approval' }], retryOnFail: false, optional: false },
      { id: 'publish', name: 'Publicacao', type: 'worker', queue: 'publishing', dependsOn: ['approval'], conditions: [], retryOnFail: true, optional: false },
    ],
  },
  review: {
    id: 'tpl-review',
    name: 'Review Comparativo',
    description: 'Review comparativo de produtos ou ferramentas',
    category: 'content',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'research', name: 'Pesquisa de Produtos', type: 'agent', agentType: 'content-intelligence', queue: 'content', dependsOn: [], conditions: [], retryOnFail: true, optional: false },
      { id: 'data-collect', name: 'Coleta de Dados', type: 'worker', queue: 'analytics', dependsOn: ['research'], conditions: [], retryOnFail: false, optional: false },
      { id: 'write-comparison', name: 'Escrita Comparativa', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['data-collect'], conditions: [], retryOnFail: true, optional: false },
      { id: 'review', name: 'Revisao Tecnica', type: 'agent', agentType: 'authority-intelligence', queue: 'content', dependsOn: ['write-comparison'], conditions: [], retryOnFail: false, optional: false },
      { id: 'publish', name: 'Publicacao', type: 'worker', queue: 'publishing', dependsOn: ['review'], conditions: [], retryOnFail: true, optional: false },
    ],
  },
  pillar: {
    id: 'tpl-pillar',
    name: 'Pagina Pilar',
    description: 'Criacao de pagina pilar com topicos e subtopicos',
    category: 'content',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'topic-research', name: 'Pesquisa de Topicos', type: 'agent', agentType: 'content-intelligence', queue: 'content', dependsOn: [], conditions: [], retryOnFail: true, optional: false },
      { id: 'keyword-analysis', name: 'Analise de Palavras-chave', type: 'agent', agentType: 'opportunity-intelligence', queue: 'analytics', dependsOn: ['topic-research'], conditions: [], retryOnFail: false, optional: false },
      { id: 'structure', name: 'Estrutura do Conteudo', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['keyword-analysis'], conditions: [], retryOnFail: false, optional: false },
      { id: 'write-pillar', name: 'Escrita do Pillar', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['structure'], conditions: [], retryOnFail: true, optional: false },
      { id: 'internal-links', name: 'Links Internos', type: 'worker', queue: 'content', dependsOn: ['write-pillar'], conditions: [], retryOnFail: false, optional: true },
      { id: 'seo-check', name: 'Verificacao SEO', type: 'agent', agentType: 'authority-intelligence', queue: 'analytics', dependsOn: ['write-pillar'], conditions: [], retryOnFail: false, optional: false },
      { id: 'publish', name: 'Publicacao', type: 'worker', queue: 'publishing', dependsOn: ['seo-check', 'internal-links'], conditions: [], retryOnFail: true, optional: false },
    ],
  },
  landing: {
    id: 'tpl-landing',
    name: 'Landing Page',
    description: 'Landing page com foco em conversao',
    category: 'content',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'research', name: 'Pesquisa de Publico', type: 'agent', agentType: 'opportunity-intelligence', queue: 'content', dependsOn: [], conditions: [], retryOnFail: true, optional: false },
      { id: 'copy', name: 'Copywriting', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['research'], conditions: [], retryOnFail: true, optional: false },
      { id: 'design', name: 'Layout', type: 'worker', queue: 'content', dependsOn: ['copy'], conditions: [], retryOnFail: false, optional: false },
      { id: 'publish', name: 'Publicacao', type: 'worker', queue: 'publishing', dependsOn: ['design'], conditions: [], retryOnFail: true, optional: false },
    ],
  },
  ebook: {
    id: 'tpl-ebook',
    name: 'E-book',
    description: 'E-book completo com pesquisa, escrita e revisao',
    category: 'content',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'research', name: 'Pesquisa Aprofundada', type: 'agent', agentType: 'content-intelligence', queue: 'content', dependsOn: [], conditions: [], retryOnFail: true, optional: false },
      { id: 'outline', name: 'Esquema', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['research'], conditions: [], retryOnFail: false, optional: false },
      { id: 'write', name: 'Escrita', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['outline'], conditions: [], retryOnFail: true, optional: false },
      { id: 'review', name: 'Revisao', type: 'agent', agentType: 'authority-intelligence', queue: 'content', dependsOn: ['write'], conditions: [], retryOnFail: false, optional: false },
      { id: 'design', name: 'Design/Layout', type: 'worker', queue: 'content', dependsOn: ['review'], conditions: [], retryOnFail: false, optional: false },
      { id: 'publish', name: 'Publicacao', type: 'worker', queue: 'publishing', dependsOn: ['design'], conditions: [], retryOnFail: true, optional: false },
    ],
  },
  newsletter: {
    id: 'tpl-newsletter',
    name: 'Newsletter',
    description: 'Newsletter com curadoria e envio',
    category: 'content',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'curate', name: 'Curadoria de Conteudos', type: 'agent', agentType: 'content-intelligence', queue: 'content', dependsOn: [], conditions: [], retryOnFail: true, optional: false },
      { id: 'write', name: 'Redacao', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['curate'], conditions: [], retryOnFail: true, optional: false },
      { id: 'review', name: 'Revisao', type: 'agent', agentType: 'authority-intelligence', queue: 'content', dependsOn: ['write'], conditions: [], retryOnFail: false, optional: false },
      { id: 'schedule', name: 'Agendamento', type: 'worker', queue: 'emails', dependsOn: ['review'], conditions: [], retryOnFail: false, optional: false },
    ],
  },
  update: {
    id: 'tpl-update',
    name: 'Atualizacao',
    description: 'Atualizacao de conteudo existente',
    category: 'maintenance',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'analysis', name: 'Analise de Performance', type: 'agent', agentType: 'predictive-intelligence', queue: 'analytics', dependsOn: [], conditions: [], retryOnFail: false, optional: false },
      { id: 'research', name: 'Nova Pesquisa', type: 'agent', agentType: 'content-intelligence', queue: 'content', dependsOn: ['analysis'], conditions: [], retryOnFail: true, optional: false },
      { id: 'update', name: 'Atualizacao', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['research'], conditions: [], retryOnFail: true, optional: false },
      { id: 'publish', name: 'Publicacao', type: 'worker', queue: 'publishing', dependsOn: ['update'], conditions: [], retryOnFail: true, optional: false },
    ],
  },
  refresh: {
    id: 'tpl-refresh',
    name: 'Refresh de Conteudo',
    description: 'Refresh completo com atualizacao de dados e reescrita',
    category: 'maintenance',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'crawl', name: 'Novo Crawling', type: 'worker', queue: 'analytics', dependsOn: [], conditions: [], retryOnFail: false, optional: false },
      { id: 'analysis', name: 'Analise de Gaps', type: 'agent', agentType: 'opportunity-intelligence', queue: 'analytics', dependsOn: ['crawl'], conditions: [], retryOnFail: false, optional: false },
      { id: 'rewrite', name: 'Reescrita', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['analysis'], conditions: [], retryOnFail: true, optional: false },
      { id: 'publish', name: 'Publicacao', type: 'worker', queue: 'publishing', dependsOn: ['rewrite'], conditions: [], retryOnFail: true, optional: false },
    ],
  },
  campaign: {
    id: 'tpl-campaign',
    name: 'Campanha Integrada',
    description: 'Campanha com multiplos canais',
    category: 'marketing',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'research', name: 'Pesquisa de Mercado', type: 'agent', agentType: 'opportunity-intelligence', queue: 'content', dependsOn: [], conditions: [], retryOnFail: true, optional: false },
      { id: 'content', name: 'Criacao de Conteudo', type: 'parallel', dependsOn: ['research'], conditions: [], retryOnFail: false, optional: false },
      { id: 'blog', name: 'Blog Post', type: 'agent', agentType: 'semantic-intelligence', queue: 'content', dependsOn: ['content'], conditions: [], retryOnFail: true, optional: false },
      { id: 'social', name: 'Social Media', type: 'worker', queue: 'content', dependsOn: ['content'], conditions: [], retryOnFail: false, optional: false },
      { id: 'email', name: 'Email Campaign', type: 'worker', queue: 'emails', dependsOn: ['content'], conditions: [], retryOnFail: false, optional: false },
      { id: 'publish-blog', name: 'Publicar Blog', type: 'worker', queue: 'publishing', dependsOn: ['blog'], conditions: [], retryOnFail: true, optional: false },
      { id: 'publish-social', name: 'Publicar Social', type: 'worker', queue: 'publishing', dependsOn: ['social'], conditions: [], retryOnFail: false, optional: false },
      { id: 'publish-email', name: 'Enviar Email', type: 'worker', queue: 'emails', dependsOn: ['email'], conditions: [], retryOnFail: false, optional: false },
      { id: 'analytics', name: 'Analise de Resultados', type: 'agent', agentType: 'predictive-intelligence', queue: 'analytics', dependsOn: ['publish-blog', 'publish-social', 'publish-email'], conditions: [], retryOnFail: false, optional: false },
    ],
  },
  seoAudit: {
    id: 'tpl-seo-audit',
    name: 'Auditoria SEO',
    description: 'Auditoria completa de SEO tecnico e conteudo',
    category: 'analytics',
    version: '1.0.0',
    status: 'ready',
    createdAt: '2026-07-03T00:00:00Z',
    steps: [
      { id: 'crawl', name: 'Crawling do Site', type: 'worker', queue: 'analytics', dependsOn: [], conditions: [], retryOnFail: false, optional: false },
      { id: 'technical', name: 'Analise Tecnica', type: 'agent', agentType: 'authority-intelligence', queue: 'analytics', dependsOn: ['crawl'], conditions: [], retryOnFail: false, optional: false },
      { id: 'content', name: 'Analise de Conteudo', type: 'agent', agentType: 'semantic-intelligence', queue: 'analytics', dependsOn: ['crawl'], conditions: [], retryOnFail: false, optional: false },
      { id: 'keywords', name: 'Analise de Palavras-chave', type: 'agent', agentType: 'opportunity-intelligence', queue: 'analytics', dependsOn: ['crawl'], conditions: [], retryOnFail: false, optional: false },
      { id: 'report', name: 'Relatorio', type: 'agent', agentType: 'content-intelligence', queue: 'analytics', dependsOn: ['technical', 'content', 'keywords'], conditions: [], retryOnFail: false, optional: false },
    ],
  },
};
