import { EnvironmentalEvent, EventType } from './environment.types';

const preloaded: EnvironmentalEvent[] = [
  { id: 'env-001', type: 'trending-topic', title: 'Turismo regenerativo em alta', description: 'Interesse crescente por turismo sustentavel no nordeste', source: 'Google Trends', impactScore: 85, riskLevel: 10, opportunityLevel: 90, urgencyScore: 75, strategicImpact: 80, confidence: 0.88, relatedWorkspaces: ['passacumaru'], suggestedMission: 'Explorar tendencia turismo regenerativo', status: 'detected', createdAt: '2026-07-03T10:00:00Z' },
  { id: 'env-002', type: 'algorithm-update', title: 'Atualizacao core algorithm Google', description: 'Google implementou mudancas no core algorithm', source: 'Search Console', impactScore: 70, riskLevel: 60, opportunityLevel: 40, urgencyScore: 80, strategicImpact: 75, confidence: 0.82, relatedWorkspaces: ['passacumaru', 'garimpeibrasil'], status: 'detected', createdAt: '2026-07-03T09:00:00Z' },
  { id: 'env-003', type: 'new-topic', title: 'Ferramentas de IA para criadores', description: 'Novo nicho de ferramentas IA para criadores de conteudo', source: 'Google Trends', impactScore: 65, riskLevel: 15, opportunityLevel: 80, urgencyScore: 50, strategicImpact: 70, confidence: 0.78, relatedWorkspaces: ['garimpeibrasil'], suggestedMission: 'Criar conteudo sobre ferramentas IA', status: 'detected', createdAt: '2026-07-03T08:00:00Z' },
  { id: 'env-004', type: 'competitive-shift', title: 'Concorrentes expandindo cluster viagens', description: '3 concorrentes lancaram conteudo similar', source: 'Competitor Monitoring', impactScore: 60, riskLevel: 55, opportunityLevel: 35, urgencyScore: 65, strategicImpact: 55, confidence: 0.85, relatedWorkspaces: ['passacumaru'], status: 'detected', createdAt: '2026-07-03T07:00:00Z' },
  { id: 'env-005', type: 'seasonality', title: 'Alta temporada de turismo junino', description: 'Sazononalidade de turismo junino se aproximando', source: 'Predictive Intelligence', impactScore: 75, riskLevel: 20, opportunityLevel: 85, urgencyScore: 70, strategicImpact: 72, confidence: 0.9, relatedWorkspaces: ['passacumaru'], suggestedMission: 'Preparar conteudo sazonal turismo junino', status: 'detected', createdAt: '2026-07-03T06:00:00Z' },
  { id: 'env-006', type: 'interest-decline', title: 'Queda interesse em dicas genericas', description: 'Reducao de 15% no trafego de dicas genericas', source: 'Google Analytics', impactScore: 50, riskLevel: 45, opportunityLevel: 30, urgencyScore: 55, strategicImpact: 48, confidence: 0.82, relatedWorkspaces: ['passacumaru', 'garimpeibrasil'], status: 'detected', createdAt: '2026-07-03T05:00:00Z' },
];

export function monitorEnvironment(): EnvironmentalEvent[] { return preloaded; }
export function getEventById(id: string): EnvironmentalEvent | undefined { return preloaded.find(e => e.id === id); }
